
-- SQL schema for Dolibarr Flotte module

CREATE TABLE llx_flotte_driver (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    ref VARCHAR(128) NOT NULL,
    entity INTEGER DEFAULT 1,
    firstname VARCHAR(128),
    middlename VARCHAR(128),
    lastname VARCHAR(128),
    address VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(50),
    employee_id VARCHAR(50),
    contract_number VARCHAR(50),
    license_number VARCHAR(50),
    license_issue_date DATE,
    license_expiry_date DATE,
    join_date DATE,
    leave_date DATE,
    password VARCHAR(128),
    department VARCHAR(128),
    status VARCHAR(50),
    gender VARCHAR(10),
    driver_image VARCHAR(255),
    documents VARCHAR(255),
    license_image VARCHAR(255),
    emergency_contact VARCHAR(255),
    fk_vehicle INTEGER,
    fk_user_author INTEGER,
    fk_user_modif INTEGER,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;

CREATE TABLE llx_flotte_vehicle (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    ref VARCHAR(128) NOT NULL,
    entity INTEGER DEFAULT 1,
    maker VARCHAR(128),
    model VARCHAR(128),
    type VARCHAR(128),
    year INTEGER,
    initial_mileage INTEGER,
    image VARCHAR(255),
    registration_expiry DATE,
    in_service TINYINT DEFAULT 1,
    department VARCHAR(128),
    engine_type VARCHAR(128),
    horsepower VARCHAR(50),
    color VARCHAR(50),
    vin VARCHAR(50),
    license_plate VARCHAR(50),
    license_expiry DATE,
    fk_group INTEGER,
    fk_user_author INTEGER,
    fk_user_modif INTEGER,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;

CREATE TABLE llx_flotte_customer (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    ref VARCHAR(128) NOT NULL,
    entity INTEGER DEFAULT 1,
    firstname VARCHAR(128),
    lastname VARCHAR(128),
    phone VARCHAR(50),
    email VARCHAR(255),
    password VARCHAR(128),
    company_name VARCHAR(255),
    tax_no VARCHAR(50),
    payment_delay INTEGER,
    gender VARCHAR(10),
    fk_user_author INTEGER,
    fk_user_modif INTEGER,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;

CREATE TABLE llx_flotte_vendor (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    ref VARCHAR(128) NOT NULL,
    entity INTEGER DEFAULT 1,
    name VARCHAR(128),
    phone VARCHAR(50),
    email VARCHAR(255),
    type VARCHAR(128),
    website VARCHAR(255),
    note TEXT,
    address1 VARCHAR(255),
    address2 VARCHAR(255),
    city VARCHAR(128),
    state VARCHAR(128),
    picture VARCHAR(255),
    fk_user_author INTEGER,
    fk_user_modif INTEGER,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;

CREATE TABLE llx_flotte_booking (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    ref VARCHAR(128) NOT NULL,
    entity INTEGER DEFAULT 1,
    fk_vehicle INTEGER,
    fk_driver INTEGER,
    fk_customer INTEGER,
    booking_date DATE,
    status VARCHAR(50),
    distance INTEGER,
    arriving_address VARCHAR(255),
    departure_address VARCHAR(255),
    buying_amount DECIMAL(10,2),
    selling_amount DECIMAL(10,2),
    fk_user_author INTEGER,
    fk_user_modif INTEGER,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;

CREATE TABLE llx_flotte_inspection (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    ref VARCHAR(128) NOT NULL,
    entity INTEGER DEFAULT 1,
    fk_vehicle INTEGER,
    registration_number VARCHAR(128),
    meter_out INTEGER,
    meter_in INTEGER,
    fuel_out VARCHAR(10),
    fuel_in VARCHAR(10),
    datetime_out DATETIME,
    datetime_in DATETIME,
    petrol_card TINYINT,
    lights_indicators TINYINT,
    inverter_cigarette TINYINT,
    mats_seats TINYINT,
    interior_damage TINYINT,
    interior_lights TINYINT,
    exterior_damage TINYINT,
    tyres_condition TINYINT,
    ladders TINYINT,
    extension_leeds TINYINT,
    power_tools TINYINT,
    ac_working TINYINT,
    headlights_working TINYINT,
    locks_alarms TINYINT,
    windows_condition TINYINT,
    seats_condition TINYINT,
    oil_check TINYINT,
    suspension TINYINT,
    toolboxes_condition TINYINT,
    fk_user_author INTEGER,
    fk_user_modif INTEGER,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;

CREATE TABLE llx_flotte_fuel (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    ref VARCHAR(128) NOT NULL,
    entity INTEGER DEFAULT 1,
    fk_vehicle INTEGER,
    date DATE,
    start_meter INTEGER,
    reference VARCHAR(128),
    state VARCHAR(128),
    note TEXT,
    complete_fillup TINYINT,
    fuel_source VARCHAR(50),
    qty DECIMAL(10,2),
    cost_unit DECIMAL(10,2),
    fk_user_author INTEGER,
    fk_user_modif INTEGER,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;

CREATE TABLE llx_flotte_workorder (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    ref VARCHAR(128) NOT NULL,
    entity INTEGER DEFAULT 1,
    fk_vehicle INTEGER,
    required_by DATE,
    reading INTEGER,
    note TEXT,
    fk_vendor INTEGER,
    status VARCHAR(50),
    price DECIMAL(10,2),
    description TEXT,
    fk_user_author INTEGER,
    fk_user_modif INTEGER,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;

CREATE TABLE llx_flotte_part_category (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    ref VARCHAR(128) NOT NULL,
    entity INTEGER DEFAULT 1,
    category_name VARCHAR(128),
    fk_user_author INTEGER,
    fk_user_modif INTEGER,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;

CREATE TABLE llx_flotte_part (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    ref VARCHAR(128) NOT NULL,
    entity INTEGER DEFAULT 1,
    barcode VARCHAR(128),
    title VARCHAR(128),
    number VARCHAR(128),
    description TEXT,
    status VARCHAR(50),
    availability TINYINT,
    fk_vendor INTEGER,
    fk_category INTEGER,
    manufacturer VARCHAR(128),
    year INTEGER,
    model VARCHAR(128),
    qty_on_hand INTEGER,
    unit_cost DECIMAL(10,2),
    note TEXT,
    picture VARCHAR(255),
    fk_user_author INTEGER,
    fk_user_modif INTEGER,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;
